# Generated by Django 3.2 on 2023-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exist'}, help_text='Required. 30 characters or fewer starting with a letter. letters', max_length=32, unique=True, verbose_name='username'),
        ),
    ]
